// Code generated by go-swagger; DO NOT EDIT.

package test

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/spplatform/kazan-backend/models"
)

// GetTestOKCode is the HTTP code returned for type GetTestOK
const GetTestOKCode int = 200

/*GetTestOK successful operation

swagger:response getTestOK
*/
type GetTestOK struct {

	/*
	  In: Body
	*/
	Payload *models.GetTestReqsponse `json:"body,omitempty"`
}

// NewGetTestOK creates GetTestOK with default headers values
func NewGetTestOK() *GetTestOK {

	return &GetTestOK{}
}

// WithPayload adds the payload to the get test o k response
func (o *GetTestOK) WithPayload(payload *models.GetTestReqsponse) *GetTestOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get test o k response
func (o *GetTestOK) SetPayload(payload *models.GetTestReqsponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTestOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTestNotFoundCode is the HTTP code returned for type GetTestNotFound
const GetTestNotFoundCode int = 404

/*GetTestNotFound not found

swagger:response getTestNotFound
*/
type GetTestNotFound struct {
}

// NewGetTestNotFound creates GetTestNotFound with default headers values
func NewGetTestNotFound() *GetTestNotFound {

	return &GetTestNotFound{}
}

// WriteResponse to the client
func (o *GetTestNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetTestInternalServerErrorCode is the HTTP code returned for type GetTestInternalServerError
const GetTestInternalServerErrorCode int = 500

/*GetTestInternalServerError internal server error

swagger:response getTestInternalServerError
*/
type GetTestInternalServerError struct {
}

// NewGetTestInternalServerError creates GetTestInternalServerError with default headers values
func NewGetTestInternalServerError() *GetTestInternalServerError {

	return &GetTestInternalServerError{}
}

// WriteResponse to the client
func (o *GetTestInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
