// Code generated by go-swagger; DO NOT EDIT.

package coupon

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetCouponIDHandlerFunc turns a function with the right signature into a get coupon ID handler
type GetCouponIDHandlerFunc func(GetCouponIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCouponIDHandlerFunc) Handle(params GetCouponIDParams) middleware.Responder {
	return fn(params)
}

// GetCouponIDHandler interface for that can handle valid get coupon ID params
type GetCouponIDHandler interface {
	Handle(GetCouponIDParams) middleware.Responder
}

// NewGetCouponID creates a new http.Handler for the get coupon ID operation
func NewGetCouponID(ctx *middleware.Context, handler GetCouponIDHandler) *GetCouponID {
	return &GetCouponID{Context: ctx, Handler: handler}
}

/*GetCouponID swagger:route GET /coupon/{id} coupon getCouponId

check coupon

*/
type GetCouponID struct {
	Context *middleware.Context
	Handler GetCouponIDHandler
}

func (o *GetCouponID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetCouponIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
