swagger: "2.0"
info:
  description: "Kazan hackathon API"
  version: "0.1.0"
  title: "Kazan API"
host: "localhost:8080"
basePath: "/api/"
schemes:
- "http"
tags:
- name: test
  description: Test tag

paths:
  /test:
    get:
      tags:
        - test
      summary: "test get endpoint"
      description: "test get endpoint for test purposes"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: body
        description: "The GitHub API url to call"
        required: true
        in: body
        schema:
          $ref: "#/definitions/GetTestRequest"
      responses:
        200:
          description: successful operation
          schema:
            $ref: "#/definitions/GetTestReqsponse"
        404:
          description: not found
        500:
          description: internal server error

definitions:
  GetTestRequest:
    type: object
    required:
    - id
    - balance
    - currency
    properties:
      id:
        type: string
      balance:
        type: number
      currency:
        type: string

  GetTestReqsponse:
    type: object
    required:
    - account-from
    - account-to
    - amount
    properties:
      account-from:
        type: string
      account-to:
        type: string
      amount:
        type: number