// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Kazan API
Kazan hackathon API


    Schemes:
      http
    Host: localhost:8080
    BasePath: /api
    Version: 0.6.2

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
