// Code generated by go-swagger; DO NOT EDIT.

package order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/spplatform/kazan-backend/models"
)

// GetOrderIDStatusOKCode is the HTTP code returned for type GetOrderIDStatusOK
const GetOrderIDStatusOKCode int = 200

/*GetOrderIDStatusOK OK

swagger:response getOrderIdStatusOK
*/
type GetOrderIDStatusOK struct {

	/*
	  In: Body
	*/
	Payload *models.OrderStatusResponse `json:"body,omitempty"`
}

// NewGetOrderIDStatusOK creates GetOrderIDStatusOK with default headers values
func NewGetOrderIDStatusOK() *GetOrderIDStatusOK {

	return &GetOrderIDStatusOK{}
}

// WithPayload adds the payload to the get order Id status o k response
func (o *GetOrderIDStatusOK) WithPayload(payload *models.OrderStatusResponse) *GetOrderIDStatusOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get order Id status o k response
func (o *GetOrderIDStatusOK) SetPayload(payload *models.OrderStatusResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOrderIDStatusOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetOrderIDStatusBadRequestCode is the HTTP code returned for type GetOrderIDStatusBadRequest
const GetOrderIDStatusBadRequestCode int = 400

/*GetOrderIDStatusBadRequest Bad request

swagger:response getOrderIdStatusBadRequest
*/
type GetOrderIDStatusBadRequest struct {
}

// NewGetOrderIDStatusBadRequest creates GetOrderIDStatusBadRequest with default headers values
func NewGetOrderIDStatusBadRequest() *GetOrderIDStatusBadRequest {

	return &GetOrderIDStatusBadRequest{}
}

// WriteResponse to the client
func (o *GetOrderIDStatusBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetOrderIDStatusNotFoundCode is the HTTP code returned for type GetOrderIDStatusNotFound
const GetOrderIDStatusNotFoundCode int = 404

/*GetOrderIDStatusNotFound Not found

swagger:response getOrderIdStatusNotFound
*/
type GetOrderIDStatusNotFound struct {
}

// NewGetOrderIDStatusNotFound creates GetOrderIDStatusNotFound with default headers values
func NewGetOrderIDStatusNotFound() *GetOrderIDStatusNotFound {

	return &GetOrderIDStatusNotFound{}
}

// WriteResponse to the client
func (o *GetOrderIDStatusNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetOrderIDStatusInternalServerErrorCode is the HTTP code returned for type GetOrderIDStatusInternalServerError
const GetOrderIDStatusInternalServerErrorCode int = 500

/*GetOrderIDStatusInternalServerError Internal server error

swagger:response getOrderIdStatusInternalServerError
*/
type GetOrderIDStatusInternalServerError struct {
}

// NewGetOrderIDStatusInternalServerError creates GetOrderIDStatusInternalServerError with default headers values
func NewGetOrderIDStatusInternalServerError() *GetOrderIDStatusInternalServerError {

	return &GetOrderIDStatusInternalServerError{}
}

// WriteResponse to the client
func (o *GetOrderIDStatusInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
