// Code generated by go-swagger; DO NOT EDIT.

package order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetOrderIDStatusHandlerFunc turns a function with the right signature into a get order ID status handler
type GetOrderIDStatusHandlerFunc func(GetOrderIDStatusParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetOrderIDStatusHandlerFunc) Handle(params GetOrderIDStatusParams) middleware.Responder {
	return fn(params)
}

// GetOrderIDStatusHandler interface for that can handle valid get order ID status params
type GetOrderIDStatusHandler interface {
	Handle(GetOrderIDStatusParams) middleware.Responder
}

// NewGetOrderIDStatus creates a new http.Handler for the get order ID status operation
func NewGetOrderIDStatus(ctx *middleware.Context, handler GetOrderIDStatusHandler) *GetOrderIDStatus {
	return &GetOrderIDStatus{Context: ctx, Handler: handler}
}

/*GetOrderIDStatus swagger:route GET /order/{id}/status order getOrderIdStatus

get order status

*/
type GetOrderIDStatus struct {
	Context *middleware.Context
	Handler GetOrderIDStatusHandler
}

func (o *GetOrderIDStatus) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetOrderIDStatusParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
