// Code generated by go-swagger; DO NOT EDIT.

package order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/spplatform/kazan-backend/models"
)

// GetOrderIDOKCode is the HTTP code returned for type GetOrderIDOK
const GetOrderIDOKCode int = 200

/*GetOrderIDOK OK

swagger:response getOrderIdOK
*/
type GetOrderIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.OrderResponse `json:"body,omitempty"`
}

// NewGetOrderIDOK creates GetOrderIDOK with default headers values
func NewGetOrderIDOK() *GetOrderIDOK {

	return &GetOrderIDOK{}
}

// WithPayload adds the payload to the get order Id o k response
func (o *GetOrderIDOK) WithPayload(payload *models.OrderResponse) *GetOrderIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get order Id o k response
func (o *GetOrderIDOK) SetPayload(payload *models.OrderResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOrderIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetOrderIDBadRequestCode is the HTTP code returned for type GetOrderIDBadRequest
const GetOrderIDBadRequestCode int = 400

/*GetOrderIDBadRequest Bad request

swagger:response getOrderIdBadRequest
*/
type GetOrderIDBadRequest struct {
}

// NewGetOrderIDBadRequest creates GetOrderIDBadRequest with default headers values
func NewGetOrderIDBadRequest() *GetOrderIDBadRequest {

	return &GetOrderIDBadRequest{}
}

// WriteResponse to the client
func (o *GetOrderIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetOrderIDNotFoundCode is the HTTP code returned for type GetOrderIDNotFound
const GetOrderIDNotFoundCode int = 404

/*GetOrderIDNotFound Not found

swagger:response getOrderIdNotFound
*/
type GetOrderIDNotFound struct {
}

// NewGetOrderIDNotFound creates GetOrderIDNotFound with default headers values
func NewGetOrderIDNotFound() *GetOrderIDNotFound {

	return &GetOrderIDNotFound{}
}

// WriteResponse to the client
func (o *GetOrderIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetOrderIDInternalServerErrorCode is the HTTP code returned for type GetOrderIDInternalServerError
const GetOrderIDInternalServerErrorCode int = 500

/*GetOrderIDInternalServerError Internal server error

swagger:response getOrderIdInternalServerError
*/
type GetOrderIDInternalServerError struct {
}

// NewGetOrderIDInternalServerError creates GetOrderIDInternalServerError with default headers values
func NewGetOrderIDInternalServerError() *GetOrderIDInternalServerError {

	return &GetOrderIDInternalServerError{}
}

// WriteResponse to the client
func (o *GetOrderIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
