// Code generated by go-swagger; DO NOT EDIT.

package order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostOrderHandlerFunc turns a function with the right signature into a post order handler
type PostOrderHandlerFunc func(PostOrderParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostOrderHandlerFunc) Handle(params PostOrderParams) middleware.Responder {
	return fn(params)
}

// PostOrderHandler interface for that can handle valid post order params
type PostOrderHandler interface {
	Handle(PostOrderParams) middleware.Responder
}

// NewPostOrder creates a new http.Handler for the post order operation
func NewPostOrder(ctx *middleware.Context, handler PostOrderHandler) *PostOrder {
	return &PostOrder{Context: ctx, Handler: handler}
}

/*PostOrder swagger:route POST /order order postOrder

create order

*/
type PostOrder struct {
	Context *middleware.Context
	Handler PostOrderHandler
}

func (o *PostOrder) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostOrderParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
