// Code generated by go-swagger; DO NOT EDIT.

package order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/spplatform/kazan-backend/models"
)

// PostOrderCreatedCode is the HTTP code returned for type PostOrderCreated
const PostOrderCreatedCode int = 201

/*PostOrderCreated Created

swagger:response postOrderCreated
*/
type PostOrderCreated struct {

	/*
	  In: Body
	*/
	Payload *models.OrderCreateResponse `json:"body,omitempty"`
}

// NewPostOrderCreated creates PostOrderCreated with default headers values
func NewPostOrderCreated() *PostOrderCreated {

	return &PostOrderCreated{}
}

// WithPayload adds the payload to the post order created response
func (o *PostOrderCreated) WithPayload(payload *models.OrderCreateResponse) *PostOrderCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post order created response
func (o *PostOrderCreated) SetPayload(payload *models.OrderCreateResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostOrderCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostOrderBadRequestCode is the HTTP code returned for type PostOrderBadRequest
const PostOrderBadRequestCode int = 400

/*PostOrderBadRequest Bad request

swagger:response postOrderBadRequest
*/
type PostOrderBadRequest struct {
}

// NewPostOrderBadRequest creates PostOrderBadRequest with default headers values
func NewPostOrderBadRequest() *PostOrderBadRequest {

	return &PostOrderBadRequest{}
}

// WriteResponse to the client
func (o *PostOrderBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostOrderInternalServerErrorCode is the HTTP code returned for type PostOrderInternalServerError
const PostOrderInternalServerErrorCode int = 500

/*PostOrderInternalServerError Internal server error

swagger:response postOrderInternalServerError
*/
type PostOrderInternalServerError struct {
}

// NewPostOrderInternalServerError creates PostOrderInternalServerError with default headers values
func NewPostOrderInternalServerError() *PostOrderInternalServerError {

	return &PostOrderInternalServerError{}
}

// WriteResponse to the client
func (o *PostOrderInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
