// Code generated by go-swagger; DO NOT EDIT.

package route

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetTicketIDRouteHandlerFunc turns a function with the right signature into a get ticket ID route handler
type GetTicketIDRouteHandlerFunc func(GetTicketIDRouteParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTicketIDRouteHandlerFunc) Handle(params GetTicketIDRouteParams) middleware.Responder {
	return fn(params)
}

// GetTicketIDRouteHandler interface for that can handle valid get ticket ID route params
type GetTicketIDRouteHandler interface {
	Handle(GetTicketIDRouteParams) middleware.Responder
}

// NewGetTicketIDRoute creates a new http.Handler for the get ticket ID route operation
func NewGetTicketIDRoute(ctx *middleware.Context, handler GetTicketIDRouteHandler) *GetTicketIDRoute {
	return &GetTicketIDRoute{Context: ctx, Handler: handler}
}

/*GetTicketIDRoute swagger:route GET /ticket/{id}/route route ticket getTicketIdRoute

get route by ticket number

*/
type GetTicketIDRoute struct {
	Context *middleware.Context
	Handler GetTicketIDRouteHandler
}

func (o *GetTicketIDRoute) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetTicketIDRouteParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
